export const GET_FILMS_LOADING = 'GET_FILMS_LOADING';
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS';
export const GET_FILMS_FAIL = 'GET_FILMS_FAIL';

export const DELETE_FILM_LOADING = 'DELETE_FILM_LOADING'
export const DELETE_FILM_SUCCESS = 'DELETE_FILM_SUCCESS'
export const DELETE_FILM_FAIL = 'DELETE_FILM_FAIL'

export const ADD_FILM_LOADING = 'ADD_FILM_LOADING';
export const ADD_FILM_SUCCESS = 'ADD_FILM_SUCCESS';
export const ADD_FILM_FAIL = 'ADD_FILM_FAIL';

export const SORT_FILMS_LOADING = 'SORT_FILMS_LOADING'
export const SORT_FILMS_SUCCESS = 'SORT_FILMS_SUCCESS'
export const SORT_FILMS_FAIL = 'SORT_FILMS_FAIL'

export const SEARCH_FILMS_LOADING = 'SEARCH_FILMS_LOADING'
export const SEARCH_FILMS_SUCCESS = 'SEARCH_FILMS_SUCCESS'
export const SEARCH_FILMS_FAIL = 'SEARCH_FILMS_FAIL'

export const IMPORT_FILE_LOADING = 'IMPORT_FILE_LOADING'
export const IMPORT_FILE_SUCCESS = 'IMPORT_FILE_SUCCESS'
export const IMPORT_FILE_FAIL = 'IMPORT_FILE_FAIL'


export const RESET_ERROR = 'RESET_ERROR'